Repository XNXKTech/laravel-redis-helper, pull requests merged in 2022-03, with the labels that each got.

#2 feat: 完善facede
  config/redis.php
  src/Facades/Redis.php
  src/Redis.php
  src/ServiceProvider.php
  src/helpers.php
  tests/Pest.php
  tests/RedisTest.php
  tests/TestCase.php
Labels: size/L

#3 refactor: update laravel framework version
  composer.json
  src/ServiceProvider.php
Labels: size/XS

#4 refactor: redis连接配置读取env
  .env.testing
  .github/workflows/tests.yml
  src/Redis.php
Labels: size/S

#5 fix: 修复默认连接配置异常
  src/Redis.php
Labels: size/XS

#7 feat: 完善hash操作
  src/Redis.php
  tests/RedisTest.php
Labels: size/M

#8 chore(workflows/tests): remove php 8.1 test
  .github/workflows/tests.yml
Labels: size/XS
